Update depends logic

diff --git a/.github/workflows/get-dependency-details.yml b/.github/workflows/get-dependency-details.yml
--- a/.github/workflows/get-dependency-details.yml
+++ b/.github/workflows/get-dependency-details.yml
@@ -46,24 +46,24 @@ jobs:
         run: |
           echo "Parsing JSON payload: '${{ inputs.payload }}'..."
           ID=""
-          if test -z "${{ inputs.payload }}"; then
+          if ! [[ -n "${{ inputs.payload }}" && $(echo '${{ inputs.payload }}' | jq 'has("${{ inputs.repo }}")') == true ]]; then
               if [ "${{ inputs.skip-version-json-check }}" = true ]; then
-                  echo "No JSON payload given and skip-version-json-check set: nothing to do"
-              else
-                  echo "No JSON payload given, using version.json"
-                  ID=$(jq -r '.dependencies."${{ inputs.repo }}"' version.json)
+                echo "No JSON payload given, and skip-version-json-check flag is set. Exiting."
+                exit 0
+              fi
+              echo "No JSON payload given, using version.json"
+              ID=$(jq -r '.dependencies."${{ inputs.repo }}"' version.json)
 
-                  echo "Searching for ${{ inputs.repo }} build id '$ID'..."
-                  if gh release view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
-                      echo "Found release build"
-                      echo "run-type=$(echo "release")" >> $GITHUB_OUTPUT
-                  elif gh run view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
-                      echo "Found non-release build"
-                      echo "run-type=$(echo "run")" >> $GITHUB_OUTPUT
-                  else
-                      echo "Build not found"
-                      exit 1
-                  fi
+              echo "Searching for ${{ inputs.repo }} build id '$ID'..."
+              if gh release view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
+                  echo "Found release build"
+                  echo "run-type=$(echo "release")" >> $GITHUB_OUTPUT
+              elif gh run view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
+                  echo "Found non-release build"
+                  echo "run-type=$(echo "run")" >> $GITHUB_OUTPUT
+              else
+                  echo "Build not found"
+                  exit 1
               fi
           else
               ID=$(echo '${{ inputs.payload }}' | jq -r '."${{ inputs.repo }}"')
